/**
 * Quick smoke tests for the dsh-desktop host internals — run with:
 *   node scripts/smoke.mjs
 * Exercises pngToIco (writes a probe ICO), config load/save round-trip, and
 * icon listing. Shortcut creation is Windows-only and intentionally NOT run
 * here (it would write to the real desktop).
 */
import { readFile, writeFile, mkdir, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const { pngToIco, listIcons, saveUserIcon, removeUserIcon, userIconDir } = await import('../packages/dsh-desktop/lib/index.mjs')
const sharp = require('..\\packages\\dsh-desktop\\node_modules\\sharp')

// A real 1x1 solid-red PNG generated by sharp (hand-written fixtures above
// were structurally invalid and failed libpng decoding).
const PNG_1x1 = await sharp({
  create: { width: 1, height: 1, channels: 4, background: { r: 255, g: 0, b: 0, alpha: 1 } },
}).png().toBuffer()

let failures = 0
function check(name, ok, detail = '') {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ` — ${detail}` : ''}`)
  if (!ok) failures++
}

// --- pngToIco ---
{
  const ico = pngToIco(PNG_1x1)
  check('pngToIco length', ico.length === 22 + PNG_1x1.length, `len=${ico.length}`)
  const view = new DataView(ico.buffer, ico.byteOffset)
  check('ico header type', view.getUint16(2, true) === 1)
  check('ico count', view.getUint16(4, true) === 1)
  check('ico size field', view.getUint32(14, true) === PNG_1x1.length)
  check('ico payload offset', view.getUint32(18, true) === 22)
  check('ico payload bytes', Buffer.from(ico.subarray(22, 26)).equals(PNG_1x1.subarray(0, 4)))
}

// --- config round-trip (under a temp DSH_HOME) ---
{
  const home = join(tmpdir(), `dsh-desktop-smoke-${Date.now()}`)
  process.env.DSH_HOME = home
  const { loadConfig, saveConfig, configPath, defaultConfig } = await import('../packages/dsh-desktop/lib/index.mjs')
  const before = await loadConfig()
  check('default config url', before.url === 'http://127.0.0.1:3080', before.url)
  check('default config port', before.port === 3080, String(before.port))
  const next = { ...defaultConfig(), url: 'http://127.0.0.1:9999', port: 9999, startCommand: ['pnpm', 'dsh', 'web'], startCwd: 'D:\\x' }
  await saveConfig(next)
  const after = await loadConfig()
  check('config round-trip url', after.url === 'http://127.0.0.1:9999', after.url)
  check('config round-trip cmd', JSON.stringify(after.startCommand) === '["pnpm","dsh","web"]', JSON.stringify(after.startCommand))
  check('config file exists', (await readFile(configPath(), 'utf8')).includes('9999'))
  await rm(home, { recursive: true, force: true })
}

// --- user icon upload + list + remove ---
{
  const home = join(tmpdir(), `dsh-desktop-smoke-${Date.now()}`)
  process.env.DSH_HOME = home
  const { saveUserIcon, removeUserIcon, userIconDir } = await import('../packages/dsh-desktop/lib/index.mjs')
  const icon = await saveUserIcon('my-icon.png', PNG_1x1)
  check('user icon stored as .ico', icon.name.endsWith('.ico'), icon.name)
  const stored = await readFile(join(userIconDir(), icon.name))
  check('user icon is valid ico container', stored.length > 22 && stored.readUInt16LE(2) === 1 && stored.readUInt32LE(14) > 0)
  const icons = await listIcons()
  check('user icon listed', icons.some(i => i.id === icon.id))
  await removeUserIcon(icon.name)
  const after = await listIcons()
  check('user icon removed', !after.some(i => i.id === icon.id))

  // Non-PNG payloads must be refused (browser half converts formats first).
  let rejected = false
  try {
    await saveUserIcon('evil.jpg', Buffer.from([0xff, 0xd8, 0xff, 0xe0, 1, 2, 3]))
  } catch {
    rejected = true
  }
  check('non-PNG upload rejected', rejected)

  // Uploaded images with a solid background get it removed automatically.
  const { removeBackground } = await import('../packages/dsh-desktop/lib/index.mjs')
  const withBg = await sharp({
    create: { width: 64, height: 64, channels: 4, background: { r: 255, g: 255, b: 255, alpha: 1 } },
  }).composite([{
    input: await sharp({
      create: { width: 32, height: 32, channels: 4, background: { r: 255, g: 0, b: 0, alpha: 1 } },
    }).png().toBuffer(),
    left: 16, top: 16,
  }]).png().toBuffer()
  const cleaned = await removeBackground(withBg)
  check('solid background removed', cleaned.length !== withBg.length || !cleaned.equals(withBg))
  // Verify the cleaned corners are transparent via raw decode.
  const raw = await sharp(cleaned).ensureAlpha().raw().toBuffer({ resolveWithObject: true })
  const cornerAlpha = raw.data[(0 * raw.info.width + 0) * 4 + 3]
  check('background corners transparent', cornerAlpha === 0, `corner alpha=${cornerAlpha}`)

  await rm(home, { recursive: true, force: true })
}

console.log(failures === 0 ? '\nAll smoke checks passed ✅' : `\n${failures} check(s) failed ❌`)
process.exit(failures === 0 ? 0 : 1)
